version: '3.7'
services:
  db:
    container_name: weather_api_ring_db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=weather_api_ring
      - POSTGRES_DB=weather_api_ring
      - POSTGRES_PASSWORD=weather_api_ring
    volumes:
      - ./.database-data:/var/lib/postgresql/data/
volumes:
  database-data:
